services:
  db:
    image: mariadb:11.5.2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rentapp
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      #to fill the database with data
      - ./api/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: